name: tagged-release

on:
  push:
    tags:
      - "v*"

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v3
        with:
          BOX_VERSION: '3.16.0'

      - name: Install dependencies
        run: |
          composer install --prefer-dist --no-progress
          composer bin box require --dev humbug/box

      - name: Build Application PHAR
        run: ./vendor/bin/box compile

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            LICENSE.txt
            build/cursedown.phar
